version: '3'
services:
  ## kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    logging:
      driver: none
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    depends_on:
      - zookeeper
    logging:
      driver: none
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  ## mqtt
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  ## redis
  redis:
    image: redis
    ports:
      - "6379:6379"

  ## mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  
  ## rabbit
  rabbit:
    image: rabbitmq:3.6
    ports:
      - "5672:5672"
    # node           : rabbit@my-rabbit
    # home dir       : /var/lib/rabbitmq
    # config file(s) : /etc/rabbitmq/rabbitmq.config
    # cookie hash    : UoNOcDhfxW9uoZ92wh6BjA==
    # log            : tty
    # sasl log       : tty
    # database dir   : /var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    hostname: my-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret cookie here"
      # RABBITMQ_DEFAULT_USER: samlet
      # RABBITMQ_DEFAULT_PASS: samlet

  ## .........


  
