version: '3.0'
services:
  duckling:
    # image: rasa/duckling:latest
    image: samlet/duckling:2019-12-22
    ports:
      - "8000:8000"

  # rasa_container:
  #   image: rasa/rasa:1.6.0-spacy-en
  sagas_container:
    image: samlet/sagas_stack:0.1
    ports:
      - 1919:1919
      # - 14000:14000
      # - 8093:8093
    volumes:
      - /pi/stack:/pi/stack
      # - ~/nltk_data:/usr/local/nltk_data
      # - /pi/ai/nltk/data:/pi/ai/nltk/data
    working_dir: /pi/stack
    # command: python -m test.simple_serv
    command: python -m sagas.tests.sanic.simple
    # command: python -m sagas.nlu.words_servant

  serv_wordnet:
    image: samlet/servant_wordnet:0.1
    ports:
      - 8093:8093

  serv_stack:
    image: samlet/servant_stack:0.1
    ports:
      - 14000:14000

  serv_zh:
    image: samlet/servant_zh:0.1
    ports:
      - 14005:14005
  serv_ja:
    image: samlet/servant_ja:0.1
    ports:
      - 14006:14006
  serv_western:
    image: samlet/servant_western:0.1
    ports:
      - 14007:14007

  ### agents and actions
  agent_servant:
    image: samlet/servant_stack:0.1
    volumes:
      - /pi/stack:/pi/stack
      - /pi/ws/sagas-ai:/pi/ws/sagas-ai
      # - /pi/ws/sagas-ai/nlu_multilang/models:/pi/ws/sagas-ai/nlu_multilang/models
    environment:
      - runtime=docker
    ports:
      - 18099:18099
    working_dir: /pi/ws/sagas-ai
    command: python -m saai.agent_servant app

  # bot with self-includeing nlu parser
  genesis_actions:
    image: rasa/rasa-sdk:latest
    volumes:
      - /pi/ws/sagas-ai/bots/genesis/actions:/app/actions
  
  # bot with multilang support
  saya_actions:
    image: rasa/rasa-sdk:latest
    volumes:
      - /pi/ws/sagas-ai/bots/saya/actions:/app/actions
      - /pi/ws/sagas-ai/bots/saya/seed:/app/seed
  saya_nlg:
    image: samlet/servant_stack:0.1
    working_dir: /pi/ws/sagas-ai
    command: python -m saai.nlg.nlg_server --domain /pi/ws/sagas-ai/bots/saya/domain.yml
  
  nlu_multilang:
    image: samlet/servant_stack:0.1
    ports:
      - 5009:5009
    working_dir: /pi/ws/sagas-ai
    command: python -m saai.multi_nlu_servant 



