version: '2'

services:
  duckling:
    # image: rasa/duckling:latest
    image: samlet/duckling:2019-12-22
    ports:
      - "8000:8000"

  # rasa_container:
  #   image: rasa/rasa:1.6.0-spacy-en
  sagas_container:
    image: samlet/sagas_stack:0.1
    ports:
      - 1919:1919
      # - 14000:14000
      # - 8093:8093
    volumes:
      - /pi/stack:/pi/stack
      # - ~/nltk_data:/usr/local/nltk_data
      # - /pi/ai/nltk/data:/pi/ai/nltk/data
    working_dir: /pi/stack
    # command: python -m test.simple_serv
    command: python -m sagas.tests.sanic.simple
    # command: python -m sagas.nlu.words_servant

  serv_wordnet:
    image: samlet/servant_wordnet:0.1
    ports:
      - 8093:8093

  serv_stack:
    image: samlet/servant_stack:0.1
    ports:
      - 14000:14000

  serv_zh:
    image: samlet/servant_zh:0.1
    ports:
      - 14005:14005



